[build]
builder = "nixpacks"

[build.nixpacksConfig]
providers = ["python"]

[build.nixpacksConfig.python]
version = "3.11"

[deploy]
startCommand = "gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 60 app_simple:app"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3