[build]
builder = "nixpacks"
buildCommand = "pwd && ls -la && pip install -r requirements.txt && cp -r ../chatbot . && chmod +x railway_start.sh && ls -la && echo 'Conteúdo do diretório chatbot:' && ls -la chatbot/"

[deploy]
startCommand = "./railway_start.sh"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3