[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt && cp -r ../chatbot ."

[deploy]
startCommand = "gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 60"
healthcheckPath = "/"
healthcheckTimeout = 100
