[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt && cp -r ../chatbot . && chmod +x railway_start.sh"

[deploy]
startCommand = "./railway_start.sh"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3